mongodb:
  - hostname: iap-aachat-prod-mdb001-1363-mongodb
    namespace: iap-aachat-prod
  - hostname: iap-ao-prod-mdb001-1363-mongodb
    namespace: iap-ao-prod
  - hostname: iap-aql-prod-mdb001-1363-mongodb
    namespace: iap-aql-prod
  - hostname: iap-bluebuddy-prod-mdb001-1363-mongodb
    namespace: iap-bluebuddy-prod
  - hostname: iap-cc-prod-mdb001-mongodb-1363
    namespace: iap-cc-prod
  - hostname: iap-cm-prod-mdb001-1363-mongodb
    namespace: iap-cm-prod
  - hostname: ocp-core-prod-mdb002-mongodb
    namespace: iap-core-prod
  - hostname: iap-dl-prod-mdb001-1363-mongodb
    namespace: iap-dl-prod
  - hostname: dw-dpmo-prod-mdb001-1363-mongodb
    namespace: iap-dpmo-prod
  - hostname: iap-dw-prod-mdb001-1363-mongodb
    namespace: iap-dw-prod
  - hostname: iap-pm-prod-mdb001-1363-mongodb
    namespace: iap-pm-prod
  - hostname: iap-procmon-prod-mdb001-1363-mongodb
    namespace: iap-procmon-prod
  - hostname: iap-prod-mdb001-mongodb-1363
    namespace: iap-prod
  - hostname: iap-sotpmi-prod-mdb001-1363-mongodb
    namespace: iap-sotpmi-prod
  - hostname: iap-sotshared-prod-mdb001-1363-mongodb
    namespace: iap-sotshared-prod
  - hostname: iap-ttc-prod-ssl-mdb001-1363-mongodb
    namespace: iap-talktocorpus-prod
    tls: 
      enabled: true
      cert_dir: /certs
mysql:
  - hostname: iap-adapter-mysql001-982
    namespace: iap-adapter-prod
  - hostname: iap-ao-prod-mysql002-982
    namespace: iap-ao-prod
  - hostname: iap-cc-prod-mysql001-982
    namespace: iap-cc-prod
  - hostname: iap-decision-prod-mysql001-982
    namespace: iap-decision-prod
  - hostname: dw-dpmo-prod-mysql001-982
    namespace: iap-dpmo-prod
  - hostname: iap-dw-prod-mysql001-982
    namespace: iap-dw-prod
  - hostname: iap-po-prod-mysql001-982
    namespace: iap-po-prod
  - hostname: iap-prod-mysql001-982
    namespace: iap-prod
  - hostname: iap-sotpmi-prod-mysql001-982
    namespace: iap-sotpmi-prod
  - hostname: iap-sotshared-prod-mysql001-982
    namespace: iap-sotshared-prod
postgresql:
  - hostname: sonar-postgresql
    namespace: iap-sonar-prod
  - hostname: iap-postgres-prod-postgresql
    namespace: iap-gai-prod
milvus:
  - hostname: iap-milvus-prod-tls-4128
    namespace: iap-ssl-prod
    tls: 
      enabled: true
      cert_dir: /milvus/configs/cert/milvus-cert
      ca_file: ca.crt
mariadb:
  - hostname: mariadb-prod
    namespace: iap-drupal-prod